[theme]
base="light"
primaryColor="#FF2442"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F5F5F5"
textColor="#333333"
font="sans serif"

[server]
headless=true
enableCORS=false
enableXsrfProtection=false
